import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import MainHeader from '../components/MainHeader/MainHeader'
import { Container, Title, Root } from '../styles/indexStyles'
import InfinityLogo from '../images/logo-infinity.svg'
import GeartechLogo from '../images/logo-geartech.svg'
import RSFLogo from '../images/RSF.svg'


const Landing: NextPage = () => {
  return (
    <>
    <Root>
    <Head>
        <title>Infinite-Gear</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
    </Head>
    
    <Container className='team' >
      <div id="resume">
        <Image src={InfinityLogo} alt="logo infinity" width={300} height={300}/>
        <br/>
        A equipe foi fundada por José Junior e Lais de Paiva na Escola SESI Canaã (Goiânia- GO- BR)no ano de 2020. No início, os membros trabalhavam em ambas as categorias (FTC e FRC). Todavia, em agosto de 2021, os membros da equipe Geartech (FTC - Ultimate Goal - 2020/21) oficializaram-se como Infinity BR, uma equipe de FRC. Atualmente, a equipe é composta por 16 membros, todos estudantes da escola SESI Canaã, e 16 mentores, que incluem engenheiros, professores, ex-alunos, patrocinadores e voluntários.
      </div>
      <div id="resume">
        <Image src={GeartechLogo} alt="logo Geartech" width={300} height={300}/>
        <br/>
        A equipe foi fundada por José Junior e Lais de Paiva na Escola SESI Canaã (Goiânia- GO- BR)no ano de 2020. No início, os membros trabalhavam em ambas as categorias (FTC e FRC). Todavia, em agosto de 2021, os membros da equipe Geartech (FTC - Ultimate Goal - 2020/21) oficializaram-se como Infinity BR, uma equipe de FRC. Atualmente, a equipe é composta por 16 membros, todos estudantes da escola SESI Canaã, e 16 mentores, que incluem engenheiros, professores, ex-alunos, patrocinadores e voluntários.
      </div>
    </Container>
    <Container className='top'>
      
      <div className='text'>
      <Title className='title'>Conheca a robótica sem fronteiras</Title> 
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores ex quisquam cumque cum culpa harum voluptatibus itaque deleniti facere deserunt vitae recusandae, maxime iste earum reiciendis vero iusto cupiditate placeat.
      
      </div>
      <div className='image'><Image alt="RSF logo" src={RSFLogo} height={500} width={500}/></div>
    </Container>
    <Container>
      
    </Container>
    
    <MainHeader/>
    </Root>
    
    </>
  )
}

export default Landing
