import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import MainHeader from '../components/MainHeader/MainHeader'
import { Container, Main, Title } from '../styles/indexStyles'
import MainBg from '../components/mainBg/MainBg'
import InfinityLogo from '../images/logo-infinity.svg'
import GeartechLogo from '../images/logo-geartech.svg'
import RSFLogo from '../images/RSF.svg'
import Button from '../components/MainHeader/Button'


const Landing: NextPage = () => {
  return (
    <>
    <Head>
        <title>Infinite-Gear</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
    </Head>
    <Container className='top'>
      
      <div className='text'>
      <Title className='title'>Conheca a robótica sem fronteiras</Title> 
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores ex quisquam cumque cum culpa harum voluptatibus itaque deleniti facere deserunt vitae recusandae, maxime iste earum reiciendis vero iusto cupiditate placeat.
      </div>
      <div className='image'><Image alt="RSF logo" src={RSFLogo}/></div>
    </Container>
    <Container>
      
    </Container>
    <MainHeader/>
    </>
  )
}

export default Landing