import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header/Header'
import { Container, ImgMain, Main, Title } from '../styles/indexStyles'
import MainBg from '../components/mainBg/MainBg'
import RSFLogo from '../images/RSF.svg'
import Button from '../components/Header/Button'


const Landing: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Infinite-Gear</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <div style={{display:"flex",height:"100vh"}}>
      <MainBg/>
      </div>
      <Main style={{position:"absolute",left:"100px",top:"150px",width:"600px"}}>
        <Title style={{justifyContent:"flex-start"}}>Conheça a Robóticas Sem Fronteiras</Title>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin maximus feugiat metus, sed feugiat 
        erat. Proin fringilla vitae tortor ut maximus. Aenean congue imperdiet mattis. In vitae eros eu 
        turpis bibendum feugiat. Cras ac nisl luctus, venenatis nibh in, pellentesque mauris. Aliquam id 
        tortor sed nisl sagittis malesuada. In hac habitasse platea dictumst. Sed accumsan et dolor id 
        pellentesque. Suspendisse pellentesque lorem felis, sed blandit sem feugiat ac. Aliquam ultrices 
        turpis a iaculis interdum. Vivamus iaculis urna sem, eu laoreet risus hendrerit vitae. Nulla lacinia 
        consequat lorem, vel sodales risus efficitur nec. Nullam vel sem a nulla condimentum facilisis non 
        in nunc. Aenean at dolor quis mauris blandit scelerisque vel vel purus. Aliquam semper dignissim 
        volutpat.
        <Button text='Saiba Mais' negative xsize={10}/>
      </Main>
      <Header/>
      
      <div>
        <Title>
          Our Mission
        </Title>
        <Main>
          <ul>
              <li>Expandir as habilidades necessárias para se tornar uma equipe competitiva na comunidade da FTC</li>

              <li>Continuar a espalhar a emoção da robótica em nossa comunidade, promovendo a formação de novas equi-
              pes da FIRST (FLL e FTC)</li>

              <li> Ajudar a inspirar e motivar colegas a buscar trabalho nas áreas de Engenharia, Tecnologia, Ciência, Arte e
              Matemática</li>
              <li>Conectar-se com empresas de engenharia, nossa comunidade local e nosso governo local e estadual</li>
              <li>Desenvolvimento de liderança de equipe, habilidades de colaboração</li>
              <li>Integrar ao máximo nossa comunidade com a robótica</li>
              <li>Passar nosso conhecimento para as equipes, principalmente as iniciantes</li>
          </ul>
        </Main>
      </div>
    </Container>
  )
}

export default Landing
