import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Landing.module.css'
import Header from '../components/Header/header'

const Landing: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Infinite-Gear</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <Header/>
    </div>
  )
}

export default Landing
